import type { Metadata } from 'next'
import '@/styles/globals.scss'
import { Providers } from './providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="zh-cn" className="dark">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
